theme: jekyll-theme-cayman
#title: Ar robot analysis
#defaults:
#  -
#    scope:
#      path: "" # an empty string here means all files in the project
#    values:
#      layout: "default"
description: 
google_analytics: 
show_downloads: true
gems:
  - jekyll-mentions
