theme: jekyll-theme-cayman
#title: Ar robot analysis
#defaults:
#  -
#    scope:
#      path: "" # an empty string here means all files in the project
#    values:
#      layout: "default"
description: 
google_analytics: 
show_downloads: true
site.github: {"zip_url":"https://github.com/Weber-Hsu/AR_robot_analysis/zipball/master"}

gems:
  - jekyll-mentions
